/* Generated by York -> C */
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <math.h>
#include <string.h>
#include <ctype.h>
#include <time.h>
#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <winsock2.h>
#include <ws2tcpip.h>
static long long __york_last_cmd = 0;
static LRESULT CALLBACK __york_wndproc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) {
    if (msg == WM_COMMAND) { __york_last_cmd = (long long)LOWORD(wParam); return 0; }
    if (msg == WM_DESTROY) { PostQuitMessage(0); return 0; }
    return DefWindowProcA(hwnd, msg, wParam, lParam);
}
static void __york_register_wndclass(void) {
    static int registered = 0;
    if (registered) return;
    WNDCLASSEXA wc = {0};
    wc.cbSize = sizeof(WNDCLASSEXA);
    wc.lpfnWndProc = __york_wndproc;
    wc.hInstance = GetModuleHandleA(NULL);
    wc.hCursor = LoadCursorA(NULL, IDC_ARROW);
    wc.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);
    wc.lpszClassName = "YorkWindowClass";
    RegisterClassExA(&wc);
    registered = 1;
}
static long long __york_window_create(const char* title, long long w, long long h) {
    __york_register_wndclass();
    int x = (GetSystemMetrics(SM_CXSCREEN) - (int)w) / 2;
    int y = (GetSystemMetrics(SM_CYSCREEN) - (int)h) / 2;
    HWND hwnd = CreateWindowExA(0, "YorkWindowClass", title ? title : "York", WS_OVERLAPPEDWINDOW | WS_VISIBLE, x, y, (int)w, (int)h, NULL, NULL, GetModuleHandleA(NULL), NULL);
    return (long long)hwnd;
}
static void __york_window_show(long long win) {
    ShowWindow((HWND)win, SW_SHOW);
    UpdateWindow((HWND)win);
}
static void __york_window_hide(long long win) { ShowWindow((HWND)win, SW_HIDE); }
static void __york_window_close(long long win) { DestroyWindow((HWND)win); }
static bool __york_window_is_open(long long win) {
    return IsWindow((HWND)win) != FALSE;
}
static void __york_window_poll_events(long long win) {
    MSG msg;
    while (PeekMessageA(&msg, NULL, 0, 0, PM_REMOVE)) {
        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }
}
static void __york_window_run_loop(long long win) {
    MSG msg;
    while (GetMessageA(&msg, NULL, 0, 0) > 0) {
        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }
}
static long long __york_window_last_command(void) {
    long long c = __york_last_cmd;
    __york_last_cmd = 0;
    return c;
}
static void __york_message_box(const char* title, const char* text) {
    MessageBoxA(NULL, text ? text : "", title ? title : "York", MB_OK);
}
static long long __york_control_button(long long win, const char* label, long long x, long long y, long long w, long long h, long long id) {
    HWND hwnd = CreateWindowExA(0, "BUTTON", label ? label : "", WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_PUSHBUTTON, (int)x, (int)y, (int)w, (int)h, (HWND)win, (HMENU)id, GetModuleHandleA(NULL), NULL);
    return (long long)hwnd;
}
static long long __york_control_label(long long win, const char* text, long long x, long long y, long long w, long long h, long long id) {
    HWND hwnd = CreateWindowExA(0, "STATIC", text ? text : "", WS_VISIBLE | WS_CHILD, (int)x, (int)y, (int)w, (int)h, (HWND)win, (HMENU)id, GetModuleHandleA(NULL), NULL);
    return (long long)hwnd;
}
static long long __york_control_textbox(long long win, const char* text, long long x, long long y, long long w, long long h, long long id) {
    HWND hwnd = CreateWindowExA(WS_EX_CLIENTEDGE, "EDIT", text ? text : "", WS_TABSTOP | WS_VISIBLE | WS_CHILD | ES_AUTOHSCROLL, (int)x, (int)y, (int)w, (int)h, (HWND)win, (HMENU)id, GetModuleHandleA(NULL), NULL);
    return (long long)hwnd;
}
static void __york_control_set_text(long long ctrl, const char* text) {
    SetWindowTextA((HWND)ctrl, text ? text : "");
}
#else
static long long __york_window_create(const char* t, long long w, long long h) { return 0; }
static void __york_window_show(long long w) {}
static void __york_window_hide(long long w) {}
static void __york_window_close(long long w) {}
static bool __york_window_is_open(long long w) { return false; }
static void __york_window_poll_events(long long w) {}
static void __york_window_run_loop(long long w) {}
static long long __york_window_last_command(void) { return 0; }
static void __york_message_box(const char* t, const char* txt) {}
static long long __york_control_button(long long w, const char* l, long long x, long long y, long long ww, long long hh, long long id) { return 0; }
static long long __york_control_label(long long w, const char* t, long long x, long long y, long long ww, long long hh, long long id) { return 0; }
static long long __york_control_textbox(long long w, const char* t, long long x, long long y, long long ww, long long hh, long long id) { return 0; }
static void __york_control_set_text(long long c, const char* t) {}
#endif

static bool __york_file(const char* path, const char* content, const char* mode) {
    FILE* f = fopen(path, mode);
    if (!f) return false;
    fputs(content, f);
    fclose(f);
    return true;
}
static bool __york_write_file(const char* path, const char* content) {
    return __york_file(path, content, "wb");
}
static bool __york_append_file(const char* path, const char* content) {
    return __york_file(path, content, "ab");
}
static bool __york_file_exists(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) return false;
    fclose(f);
    return true;
}
static const char* __york_read_file(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) return "";
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (sz < 0) { fclose(f); return ""; }
    char* buf = (char*)malloc((size_t)sz + 1);
    if (!buf) { fclose(f); return ""; }
    size_t r = fread(buf, 1, (size_t)sz, f);
    buf[r] = 0;
    fclose(f);
    return buf;
}

static const char* __york_strcat(const char* a, const char* b) {
    size_t la = strlen(a), lb = strlen(b);
    char* out = (char*)malloc(la + lb + 1);
    memcpy(out, a, la);
    memcpy(out + la, b, lb);
    out[la + lb] = 0;
    return out;
}
static size_t __york_strlen(const char* s) {
    return s ? strlen(s) : 0;
}
static const char* __york_to_string_int(long long v) {
    char* buf = (char*)malloc(32);
    snprintf(buf, 32, "%lld", v);
    return buf;
}
static const char* __york_to_string_float(double v) {
    char* buf = (char*)malloc(32);
    snprintf(buf, 32, "%g", v);
    return buf;
}
static const char* __york_to_string_bool(bool v) {
    return v ? "true" : "false";
}
static long long __york_to_int(const char* s) {
    return s ? atoll(s) : 0;
}
static double __york_to_float(const char* s) {
    return s ? atof(s) : 0.0;
}
static int __york_exec(const char* cmd) {
    return system(cmd);
}
static void __york_exit(int code) {
    exit(code);
}
static long long __york_bin_pack(const char* path, const char* data) {
    FILE* f = fopen(path ? path : "data.ybin", "wb");
    if (!f) return 0;
    size_t len = data ? strlen(data) : 0;
    fwrite(&len, sizeof(size_t), 1, f);
    if (len > 0) fwrite(data, 1, len, f);
    fclose(f);
    return (long long)len;
}
static const char* __york_crypto_hash(const char* input) {
    unsigned long hash = 5381;
    if (input) { int c; while ((c = *input++)) hash = ((hash << 5) + hash) + c; }
    static char buf[32];
    snprintf(buf, sizeof(buf), "%lx", hash);
    return buf;
}
static long long __york_net_listen(long long port) {
    #ifdef _WIN32
    WSADATA wsa; WSAStartup(MAKEWORD(2,2), &wsa);
    #endif
    int s = socket(AF_INET, SOCK_STREAM, 0);
    if (s < 0) return -1;
    int opt = 1; setsockopt(s, SOL_SOCKET, SO_REUSEADDR, (char*)&opt, sizeof(opt));
    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons((unsigned short)port);
    if (bind(s, (struct sockaddr*)&addr, sizeof(addr)) < 0) { return -1; }
    if (listen(s, 128) < 0) { return -1; }
    return (long long)s;
}
static long long __york_net_accept(long long server_sock) {
    struct sockaddr_in client_addr;
    int client_len = sizeof(client_addr);
    int cs = accept((int)server_sock, (struct sockaddr*)&client_addr, &client_len);
    return (long long)cs;
}
static long long __york_net_connect(const char* host, long long port) {
    #ifdef _WIN32
    WSADATA wsa; WSAStartup(MAKEWORD(2,2), &wsa);
    #endif
    int s = socket(AF_INET, SOCK_STREAM, 0);
    if (s < 0) return -1;
    struct hostent* he = gethostbyname(host ? host : "localhost");
    if (!he) return -1;
    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    memcpy(&addr.sin_addr, he->h_addr_list[0], he->h_length);
    addr.sin_port = htons((unsigned short)port);
    if (connect(s, (struct sockaddr*)&addr, sizeof(addr)) < 0) { return -1; }
    return (long long)s;
}
static long long __york_net_send(long long sock, const char* data) {
    if (!data) return 0;
    return (long long)send((int)sock, data, (int)strlen(data), 0);
}
static const char* __york_net_recv(long long sock) {
    char* buf = (char*)malloc(4096);
    if (!buf) return "";
    int r = recv((int)sock, buf, 4095, 0);
    if (r <= 0) { free(buf); return ""; }
    buf[r] = '\0';
    return buf;
}
static void __york_net_close(long long sock) {
    #ifdef _WIN32
    closesocket((int)sock);
    #else
    close((int)sock);
    #endif
}
static long long __york_read_int(void) {
    char* l = __york_read_line();
    return atoll(l);
}
static const char* __york_str_upper(const char* s) {
    if (!s) return "";
    size_t n = strlen(s);
    char* out = (char*)malloc(n + 1);
    for (size_t i = 0; i < n; i++) out[i] = (char)toupper((unsigned char)s[i]);
    out[n] = '\0';
    return out;
}
static const char* __york_str_lower(const char* s) {
    if (!s) return "";
    size_t n = strlen(s);
    char* out = (char*)malloc(n + 1);
    for (size_t i = 0; i < n; i++) out[i] = (char)tolower((unsigned char)s[i]);
    out[n] = '\0';
    return out;
}
static const char* __york_str_trim(const char* s) {
    if (!s) return "";
    size_t n = strlen(s), a = 0, z = n;
    while (a < z && isspace((unsigned char)s[a])) a++;
    while (z > a && isspace((unsigned char)s[z - 1])) z--;
    char* out = (char*)malloc(z - a + 1);
    memcpy(out, s + a, z - a);
    out[z - a] = '\0';
    return out;
}
static bool __york_str_contains(const char* s, const char* sub) {
    return s && sub ? strstr(s, sub) != NULL : false;
}
static bool __york_str_starts(const char* s, const char* pre) {
    if (!s || !pre) return false;
    return strncmp(s, pre, strlen(pre)) == 0;
}
static bool __york_str_ends(const char* s, const char* suf) {
    if (!s || !suf) return false;
    size_t ls = strlen(s), lf = strlen(suf);
    return lf > ls ? false : strcmp(s + ls - lf, suf) == 0;
}
static const char* __york_str_sub(const char* s, long long start, long long end) {
    if (!s) return "";
    size_t n = strlen(s);
    long long a = start < 0 ? 0 : start; if (a > (long long)n) a = n;
    long long z = end < 0 ? (long long)n : end; if (z > (long long)n) z = n; if (z < a) z = a;
    size_t len = (size_t)(z - a);
    char* out = (char*)malloc(len + 1);
    memcpy(out, s + a, len);
    out[len] = '\0';
    return out;
}
static long long __york_str_index(const char* s, const char* sub) {
    if (!s || !sub) return -1;
    char* p = strstr(s, sub);
    return p ? (long long)(p - s) : -1;
}
static long long __york_str_last_index(const char* s, const char* sub) {
    if (!s || !sub) return -1;
    size_t ls = strlen(s), lb = strlen(sub);
    if (lb > ls || lb == 0) return -1;
    for (long long i = (long long)(ls - lb); i >= 0; i--) {
        if (strncmp(s + i, sub, lb) == 0) return i;
    }
    return -1;
}
static const char* __york_str_char_at(const char* s, long long i) {
    if (!s || i < 0 || (size_t)i >= strlen(s)) return "";
    char* out = (char*)malloc(2);
    out[0] = s[i]; out[1] = '\0';
    return out;
}
static const char* __york_str_repeat(const char* s, long long n) {
    if (!s || n <= 0) return "";
    size_t len = strlen(s);
    char* out = (char*)malloc(len * (size_t)n + 1);
    if (!out) return "";
    for (long long i = 0; i < n; i++) memcpy(out + (size_t)i * len, s, len);
    out[len * (size_t)n] = '\0';
    return out;
}
static bool __york_str_empty(const char* s) {
    return !s || s[0] == '\0';
}
static const char* __york_str_replace(const char* s, const char* from, const char* to) {
    if (!s || !from || !*from) return s ? s : "";
    size_t n = strlen(s), lf = strlen(from), lt = strlen(to);
    size_t cnt = 0; const char* p = s;
    while ((p = strstr(p, from)) != NULL) { cnt++; p += lf; }
    if (cnt == 0) return s;
    size_t out_sz = n - cnt * lf + cnt * lt + 1;
    char* out = (char*)malloc(out_sz);
    if (!out) return s;
    char* w = out; p = s;
    for (size_t i = 0; i < cnt; i++) {
        char* hit = strstr(p, from);
        size_t pre = (size_t)(hit - p);
        memcpy(w, p, pre); w += pre;
        memcpy(w, to, lt); w += lt;
        p = hit + lf;
    }
    strcpy(w, p);
    return out;
}
static const char* __york_str_reverse(const char* s) {
    if (!s) return "";
    size_t n = strlen(s);
    char* out = (char*)malloc(n + 1);
    for (size_t i = 0; i < n; i++) out[i] = s[n - 1 - i];
    out[n] = '\0';
    return out;
}
static const char* __york_str_trim_start(const char* s) {
    if (!s) return "";
    const char* p = s;
    while (*p && isspace((unsigned char)*p)) p++;
    return __york_str_sub(p, 0, (long long)strlen(p));
}
static const char* __york_str_trim_end(const char* s) {
    if (!s) return "";
    size_t n = strlen(s);
    size_t z = n;
    while (z > 0 && isspace((unsigned char)s[z - 1])) z--;
    return __york_str_sub(s, 0, (long long)z);
}
static long long __york_now(void) {
    struct timespec ts;
    timespec_get(&ts, TIME_UTC);
    return (long long)ts.tv_sec * 1000 + ts.tv_nsec / 1000000;
}
static const char* __york_env(const char* key) {
    const char* v = key ? getenv(key) : NULL;
    return v ? v : "";
}
static const char* __york_platform_name(void) {
    #if defined(_WIN32)
    return "windows";
    #elif defined(__APPLE__)
    return "macos";
    #elif defined(__linux__)
    return "linux";
    #elif defined(__FreeBSD__)
    return "freebsd";
    #else
    return "unknown";
    #endif
}
static long long __york_random_range(long long lo, long long hi) {
    if (hi <= lo) return lo;
    long long span = hi - lo;
    return lo + (long long)(rand() / (RAND_MAX / span + 1));
}
static long long __york_str_count(const char* s, const char* sub) {
    if (!s || !sub || !*sub) return 0;
    long long n = 0;
    size_t l = strlen(sub);
    const char* p = s;
    while ((p = strstr(p, sub)) != NULL) { n++; p += l; }
    return n;
}
static const char* __york_str_pad_left(const char* s, long long width, const char* pad) {
    if (!s) return "";
    size_t n = strlen(s), pl = pad ? strlen(pad) : 0;
    if (pl == 0) pl = 1;
    if ((size_t)width <= n) return s;
    size_t need = (size_t)width - n;
    char* out = (char*)malloc((size_t)width + 1);
    if (!out) return s;
    for (size_t i = 0; i < need; i++) out[i] = pad ? pad[i % pl] : ' ';
    memcpy(out + need, s, n);
    out[(size_t)width] = '\0';
    return out;
}
static const char* __york_str_pad_right(const char* s, long long width, const char* pad) {
    if (!s) return "";
    size_t n = strlen(s), pl = pad ? strlen(pad) : 0;
    if (pl == 0) pl = 1;
    if ((size_t)width <= n) return s;
    size_t need = (size_t)width - n;
    char* out = (char*)malloc((size_t)width + 1);
    if (!out) return s;
    memcpy(out, s, n);
    for (size_t i = 0; i < need; i++) out[n + i] = pad ? pad[i % pl] : ' ';
    out[(size_t)width] = '\0';
    return out;
}
static long long __york_math_min_i(long long a, long long b) { return a < b ? a : b; }
static long long __york_math_max_i(long long a, long long b) { return a > b ? a : b; }
static double __york_math_min_f(double a, double b) { return a < b ? a : b; }
static double __york_math_max_f(double a, double b) { return a > b ? a : b; }
static long long __york_math_clamp_i(long long x, long long lo, long long hi) { return x < lo ? lo : (x > hi ? hi : x); }
static double __york_math_clamp_f(double x, double lo, double hi) { return x < lo ? lo : (x > hi ? hi : x); }
static void __york_sleep(unsigned long long ms) {
    if (ms == 0) return;
    #ifdef _WIN32
    Sleep((DWORD)ms);
    #else
    struct timespec ts;
    ts.tv_sec = (time_t)(ms / 1000);
    ts.tv_nsec = (long)((ms % 1000) * 1000000ULL);
    nanosleep(&ts, NULL);
    #endif
}



int main(void);

int main(void) {
    printf("York High-Performance Engine v0.2.5\n");
    long long bytes = __york_bin_pack("user.ybin", "ID:4920,Role:Admin,Token:XYZ789");
    printf("%s\n", __york_strcat("Packed bytes to .ybin: ", __york_to_string_int(bytes)));
    const char* hash = __york_crypto_hash("YorkSystemsProgramming2026");
    printf("%s\n", __york_strcat("Secure Hash Check: ", hash));
    long long server = __york_net_listen(9000);
    printf("%s\n", __york_strcat(__york_strcat("Network Listener active on port 9000 (socket handle: ", __york_to_string_int(server)), ")"));
    __york_net_close(server);
    long long win = __york_window_create("York v0.2.5 Enterprise", 640, 480);
    long long btn = __york_control_button(win, "Execute Task", 50, 50, 150, 40, 101);
    __york_window_show(win);
    __york_message_box("York v0.2.5", "Enterprise Engine initialized successfully!");
    __york_window_close(win);
    return 0;
}

