/* Generated by York -> C */
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <math.h>
#include <string.h>

static bool __york_file(const char* path, const char* content, const char* mode) {
    FILE* f = fopen(path, mode);
    if (!f) return false;
    fputs(content, f);
    fclose(f);
    return true;
}
static bool __york_write_file(const char* path, const char* content) {
    return __york_file(path, content, "wb");
}
static bool __york_append_file(const char* path, const char* content) {
    return __york_file(path, content, "ab");
}

static const char* __york_strcat(const char* a, const char* b) {
    size_t la = strlen(a), lb = strlen(b);
    char* out = (char*)malloc(la + lb + 1);
    memcpy(out, a, la);
    memcpy(out + la, b, lb);
    out[la + lb] = 0;
    return out;
}

void line(const char* text);
void head();
void nav();
void hero();
void features();
void feature(const char* title, const char* desc);
void codeblock();
void code();
void install();
void footer();
int main(void);

void line(const char* text) {
    __york_append_file("index.html", text);
    __york_append_file("index.html", "\n");
}

void head() {
    line("<!DOCTYPE html>");
    line("<html lang='en'>");
    line("<head>");
    line("<meta charset='utf-8'>");
    line("<meta name='viewport' content='width=device-width, initial-scale=1'>");
    line("<title>York — a fast, friendly systems language</title>");
    line("<link rel='icon' href='data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><rect width=%22100%22 height=%22100%22 rx=%2220%22 fill=%22%230d1b2e%22/><text x=%2250%22 y=%2268%22 font-size=%2260%22 text-anchor=%22middle%22 fill=%22%2367e8f9%22 font-family=%22monospace%22>Y</text></svg>'>");
    line("<style>");
    line("* { margin: 0; padding: 0; box-sizing: border-box; }");
    line("body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: #0b0f1a; color: #e6edf3; line-height: 1.6; }");
    line("a { color: #67e8f9; text-decoration: none; }");
    line("a:hover { text-decoration: underline; }");
    line(".nav { position: sticky; top: 0; display: flex; align-items: center; gap: 24px; padding: 14px 40px; background: rgba(11,15,26,.9); backdrop-filter: blur(10px); border-bottom: 1px solid #1d2a3a; z-index: 10; }");
    line(".nav .logo { font-weight: 700; font-size: 1.3rem; letter-spacing: .5px; }");
    line(".nav .logo span { color: #67e8f9; }");
    line(".nav a { color: #8aa0b8; font-size: .95rem; }");
    line(".nav .spacer { flex: 1; }");
    line(".nav .cta { background: #155e75; color: white !important; padding: 8px 18px; border-radius: 8px; font-weight: 600; }");
    line(".nav .cta:hover { background: #0e7490; text-decoration: none; }");
    line(".hero { padding: 110px 40px 80px; text-align: center; background: radial-gradient(1200px 500px at 50% -100px, #122a41 0%, transparent 70%); }");
    line(".hero h1 { font-size: 4rem; font-weight: 800; letter-spacing: -1px; }");
    line(".hero h1 span { background: linear-gradient(90deg, #67e8f9, #a78bfa); -webkit-background-clip: text; background-clip: text; color: transparent; }");
    line(".hero p.lead { font-size: 1.35rem; color: #a9b7c6; max-width: 640px; margin: 22px auto 36px; }");
    line(".buttons { display: flex; gap: 16px; justify-content: center; flex-wrap: wrap; }");
    line(".btn { padding: 14px 26px; border-radius: 10px; font-weight: 600; font-size: 1rem; }");
    line(".btn.primary { background: #155e75; color: white; }");
    line(".btn.primary:hover { background: #0e7490; text-decoration: none; }");
    line(".btn.ghost { border: 1px solid #2d3d52; color: #c9d6e3; }");
    line(".btn.ghost:hover { background: #16223a; text-decoration: none; }");
    line("section { padding: 70px 40px; max-width: 1080px; margin: 0 auto; }");
    line("section h2 { font-size: 2rem; margin-bottom: 16px; text-align: center; }");
    line("section.sub h2 { text-align: center; }");
    line("section p.desc { color: #a9b7c6; text-align: center; max-width: 640px; margin: 0 auto 44px; }");
    line(".grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 24px; }");
    line(".card { background: #101a2c; border: 1px solid #1d2a3a; border-radius: 14px; padding: 26px; }");
    line(".card h3 { color: #67e8f9; margin-bottom: 10px; }");
    line(".card p { color: #9fb0c3; font-size: .95rem; }");
    line("pre { background: #0d1626; border: 1px solid #1d2a3a; border-radius: 14px; padding: 26px; overflow-x: auto; font-family: 'Cascadia Code', 'Fira Code', Consolas, monospace; font-size: .92rem; line-height: 1.55; }");
    line("pre .k { color: #c792ea; }");
    line("pre .t { color: #6db3ff; }");
    line("pre .s { color: #c3e88d; }");
    line("pre .f { color: #f78c6c; }");
    line("pre .c { color: #5c6773; }");
    line(".codecols { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; align-items: start; }");
    line("@media (max-width: 800px) { .codecols { grid-template-columns: 1fr; } }");
    line(".install { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }");
    line("@media (max-width: 800px) { .install { grid-template-columns: 1fr; } }");
    line(".install .card h3 { margin-bottom: 14px; }");
    line("code.inline { background: #1d2a3a; padding: 2px 7px; border-radius: 5px; font-size: .9em; font-family: 'Cascadia Code', Consolas, monospace; }");
    line(".footer { border-top: 1px solid #1d2a3a; padding: 34px 40px; text-align: center; color: #5c6773; font-size: .9rem; }");
    line(".footer a { color: #8aa0b8; }");
    line("</style>");
    line("</head>");
    line("<body>");
}

void nav() {
    line("<div class='nav'>");
    line("<div class='logo'>York<span>.</span></div>");
    line("<a href='#features'>Features</a>");
    line("<a href='#code'>Code</a>");
    line("<a href='#install'>Install</a>");
    line("<a href='https://github.com/york-lang/york'>GitHub</a>");
    line("<div class='spacer'></div>");
    line("<a class='cta' href='#install'>Get started</a>");
    line("</div>");
}

void hero() {
    line("<div class='hero'>");
    line("<h1>The speed of <span>C</span>,<br>the feel of <span>Java &amp; JS</span>.</h1>");
    line("<p class='lead'>York is a fast, simple systems language. Write clean, familiar code, compile to a single native binary — no runtime, no garbage collector, no classes.</p>");
    line("<div class='buttons'>");
    line("<a class='btn primary' href='#install'>Install York</a>");
    line("<a class='btn ghost' href='#code'>See the code</a>");
    line("</div>");
    line("</div>");
}

void features() {
    line("<section id='features' class='sub'>");
    line("<h2>Built for how you actually code</h2>");
    line("<p class='desc'>Syntax you already know, performance you expect, zero magic under the hood.</p>");
    line("<div class='grid'>");
    feature("Familiar syntax", "Java and JavaScript style: typed params, this, method calls, for loops — no boilerplate, no ceremony.");
    feature("No classes, no clutter", "Plain structs for data, impl blocks for methods, traits for behavior. Composition beats inheritance, always.");
    feature("Arena memory", "Stack-like arena allocation with stash semantics. Fast, predictable, and trivially safe — no GC pauses, ever.");
    feature("Single native binary", "York compiles straight to C and then to your platform's native code. Drop the binary anywhere; it just runs.");
    feature("WebAssembly on deck", "Compile the same York source to WebAssembly for the browser. One language, native speed, everywhere.");
    feature("One-command install", "A tiny installer drops york on your PATH. No Rust toolchain, no giant SDK, no fuss.");
    line("</div>");
    line("</section>");
}

void feature(const char* title, const char* desc) {
    line("<div class='card'>");
    line(__york_strcat(__york_strcat("<h3>", title), "</h3>"));
    line(__york_strcat(__york_strcat("<p>", desc), "</p>"));
    line("</div>");
}

void codeblock() {
    line("<pre>");
    line("<span class='c'>// hello in York</span>");
    line("<span class='k'>public static void</span> <span class='f'>main</span>(<span class='t'>String</span>[] args) {");
    line("<span class='t'>Arena</span>&lt;<span class='t'>Player</span>&gt; players = <span class='k'>new</span> <span class='t'>Arena</span>(1000);");
    line("players.<span class='f'>push</span>(<span class='t'>Player</span> { pos: 1.0, hp: 100.0 });");
    line("");
    line("<span class='k'>for</span> (<span class='t'>Player</span> p : players) {");
    line("    p.<span class='f'>damage</span>(10.0);");
    line("    <span class='f'>println</span>(p.hp);");
    line("}");
    line("}");
    line("</pre>");
}

void code() {
    line("<section id='code' class='sub'>");
    line("<h2>Write it the way you already think</h2>");
    line("<p class='desc'>Value semantics by default. When you read from an arena you get a copy — mutation is explicit.</p>");
    line("<div class='codecols'>");
    line("<div>");
    codeblock();
    line("</div>");
    line("<div>");
    line("<pre class='c'>");
    line("<span class='k'>struct</span> <span class='t'>Player</span> {");
    line("    <span class='t'>float</span> pos;");
    line("    <span class='t'>float</span> hp;");
    line("}");
    line("");
    line("<span class='k'>impl</span> <span class='t'>Player</span> {");
    line("    <span class='t'>void</span> <span class='f'>damage</span>(<span class='t'>float</span> amount) {");
    line("        <span class='k'>this</span>.hp -= amount;");
    line("        <span class='k'>if</span> (<span class='k'>this</span>.hp &lt; 0.0) { <span class='k'>this</span>.hp = 0.0; }");
    line("    }");
    line("}");
    line("</pre>");
    line("</div>");
    line("</div>");
    line("</section>");
}

void install() {
    line("<section id='install' class='sub'>");
    line("<h2>Install in one command</h2>");
    line("<p class='desc'>No Rust toolchain required. Pick your platform and go.</p>");
    line("<div class='install'>");
    line("<div class='card'>");
    line("<h3>Windows</h3>");
    line("<pre>irm https://raw.githubusercontent.com/york-lang/york/main/installers/install.ps1 | iex</pre>");
    line("</div>");
    line("<div class='card'>");
    line("<h3>macOS / Linux</h3>");
    line("<pre>curl -fsSL https://raw.githubusercontent.com/york-lang/york/main/installers/install.sh | sh</pre>");
    line("</div>");
    line("</div>");
    line("<p style='text-align:center; color:#9fb0c3; margin-top:28px;'>Then <code class='inline'>york new hello</code> creates a project, and <code class='inline'>york run</code> compiles &amp; runs it.</p>");
    line("</section>");
}

void footer() {
    line("<div class='footer'>");
    line("York is an open-source project. Written by humans, compiled to native.");
    line("<br><a href='https://github.com/york-lang/york'>github.com/york-lang/york</a>");
    line("</div>");
    line("</body>");
    line("</html>");
}

int main(void) {
    head();
    nav();
    hero();
    features();
    code();
    install();
    footer();
    printf("Site written to index.html\n");
    return 0;
}

